/**
 * Highlight known AI-style and human-style phrases in text.
 * Phrase lists kept in sync with server/utils/heuristic.js
 */

export const AI_PHRASES = [
  "as an ai",
  "as a language model",
  "as an ai language model",
  "as an artificial intelligence",
  "as an ai system",
  "as a machine learning model",
  "as a generative ai",
  "i am an ai",
  "i'm an ai",
  "i am a language model",
  "i'm a language model",
  "i do not have personal",
  "i don't have personal",
  "i do not have feelings",
  "i don't have feelings",
  "i do not have emotions",
  "i don't have emotions",
  "i cannot express personal",
  "i can't express personal",
  "i cannot provide personal",
  "i can't provide personal",
  "i cannot experience",
  "i can't experience",
  "i do not possess personal",
  "i don't possess personal",
  "my training data",
  "my knowledge cutoff",
  "based on my training",
  "according to my training",
  "i was trained",
  "i have been trained",
  "in this passage",
  "in this article",
  "in this essay",
  "in this discussion",
  "in this section",
  "this passage explores",
  "this article explores",
  "this essay explores",
  "this discussion explores",
  "this topic explores",
  "this section discusses",
  "the following discussion",
  "the following sections",
  "in the following sections",
  "this overview",
  "this comprehensive overview",
  "this guide provides",
  "this article provides",
  "this essay provides",
  "this discussion provides",
  "it is important to note",
  "it is worth noting",
  "it should be noted",
  "it is crucial to",
  "it is essential to",
  "it is important that",
  "it is worth mentioning",
  "it should also be noted",
  "needless to say",
  "in conclusion",
  "to conclude",
  "in summary",
  "to summarize",
  "in essence",
  "overall",
  "ultimately",
  "notably",
  "significantly",
  "interestingly",
  "furthermore",
  "moreover",
  "additionally",
  "in addition",
  "likewise",
  "consequently",
  "therefore",
  "thus",
  "hence",
  "accordingly",
  "as a result",
  "for this reason",
  "in other words",
  "that is to say",
  "in particular",
  "particularly",
  "specifically",
  "generally speaking",
  "broadly speaking",
  "more specifically",
  "in contrast",
  "by contrast",
  "on the other hand",
  "conversely",
  "alternatively",
  "similarly",
  "in comparison",
  "with this in mind",
  "with that in mind",
  "that being said",
  "having said that",
  "taking into account",
  "taking this into consideration",
  "from this perspective",
  "from this point of view",
  "in this context",
  "in this regard",
  "in this respect",
  "in today's digital age",
  "in today's fast-paced world",
  "in today's rapidly changing world",
  "in today's modern world",
  "in the modern era",
  "in the digital age",
  "in the realm of",
  "in the world of",
  "in the landscape of",
  "in the ever-evolving landscape",
  "in an increasingly digital world",
  "in an increasingly connected world",
  "in an increasingly complex world",
  "in our rapidly changing world",
  "as technology continues to evolve",
  "as society continues to evolve",
  "as the world continues to evolve",
  "delve into",
  "delving into",
  "dive into",
  "diving into",
  "explore the world of",
  "exploring the world of",
  "shed light on",
  "provide valuable insights",
  "valuable insights into",
  "gain a deeper understanding",
  "deeper understanding of",
  "a comprehensive understanding",
  "a comprehensive overview",
  "a detailed overview",
  "a thorough understanding",
  "a closer look at",
  "tapestry",
  "multifaceted",
  "myriad",
  "plethora",
  "plethora of",
  "abundance of",
  "array of",
  "wide array of",
  "vast array of",
  "wide range of",
  "a wide range of",
  "a variety of",
  "a multitude of",
  "myriad of",
  "numerous ways",
  "diverse range",
  "dynamic landscape",
  "complex landscape",
  "evolving landscape",
  "intricate",
  "nuanced",
  "multidimensional",
  "holistic",
  "comprehensive",
  "robust",
  "seamless",
  "cutting-edge",
  "state-of-the-art",
  "innovative",
  "groundbreaking",
  "transformative",
  "revolutionary",
  "game-changer",
  "game changer",
  "paradigm shift",
  "synergy",
  "synergies",
  "ecosystem",
  "empower",
  "empowers",
  "empowering",
  "leverage",
  "leveraging",
  "utilize",
  "utilizing",
  "facilitate",
  "facilitates",
  "foster",
  "fosters",
  "fostering",
  "enhance",
  "enhances",
  "enhancing",
  "optimize",
  "optimizing",
  "optimise",
  "optimising",
  "streamline",
  "streamlining",
  "unlock the potential",
  "unlocking the potential",
  "harness the power",
  "harnessing the power",
  "pave the way",
  "paving the way",
  "plays a crucial role",
  "play a crucial role",
  "plays an important role",
  "play an important role",
  "plays a vital role",
  "play a vital role",
  "plays a significant role",
  "play a significant role",
  "serves as a",
  "serve as a",
  "acts as a",
  "act as a",
  "stands as a testament",
  "serves as a testament",
  "underscores the importance",
  "highlighting the importance",
  "highlights the importance",
  "emphasizes the importance",
  "emphasises the importance",
  "demonstrates the importance",
  "reflects the importance",
  "contributes to",
  "contributes significantly",
  "offers a unique opportunity",
  "provides an opportunity",
  "presents an opportunity",
  "opens up new possibilities",
  "opens the door to",
  "lay the foundation",
  "lays the foundation",
  "building a foundation",
  "drives innovation",
  "driving innovation",
  "fosters innovation",
  "promotes innovation",
  "in conclusion",
  "to conclude",
  "in summary",
  "to summarize",
  "in short",
  "in essence",
  "all in all",
  "overall,",
  "ultimately,",
  "taken together",
  "when considered together",
  "considering these factors",
  "based on the above",
  "in light of the above",
  "in light of these considerations",
  "with these considerations in mind",
  "the key takeaway",
  "the key takeaway is",
  "the main takeaway",
  "the main takeaway is",
  "it is clear that",
  "it becomes clear that",
  "this demonstrates that",
  "this highlights that",
  "this shows that",
  "it is safe to say",
  "one might argue",
  "it can be argued",
  "it could be argued",
  "it is reasonable to suggest",
  "it is reasonable to assume",
  "it is important to consider",
  "it is worth considering",
  "it is important to recognize",
  "it is important to recognise",
  "it is essential to understand",
  "it is crucial to understand",
  "it is useful to consider",
  "it is helpful to consider",
  "from a broader perspective",
  "from a practical perspective",
  "from a theoretical perspective",
  "from a broader standpoint",
  "in practical terms",
  "in theoretical terms",
  "moving forward",
  "going forward",
  "as we move forward",
  "looking ahead",
  "in the years to come",
  "in the future",
  "future developments",
  "future possibilities",
  "future applications",
  "continued advancements",
  "ongoing advancements",
  "continued innovation",
  "as technology advances",
  "as technology continues",
  "the future of",
  "shaping the future",
  "shape the future",
  "paving the way for future",
  "numerous benefits",
  "several benefits",
  "key benefits",
  "significant benefits",
  "potential benefits",
  "a number of benefits",
  "offers several advantages",
  "offers numerous advantages",
  "provides several advantages",
  "provides numerous advantages",
  "key advantages",
  "significant advantages",
  "potential advantages",
  "challenges and opportunities",
  "challenges and benefits",
  "advantages and disadvantages",
  "pros and cons",
  "potential challenges",
  "potential limitations",
  "key challenges",
  "significant challenges",
  "several challenges",
  "various challenges",
  "a number of challenges",
  "despite the challenges",
  "despite the limitations",
  "for example",
  "for instance",
  "as an example",
  "as a result",
  "this means that",
  "this allows",
  "this enables",
  "this helps to",
  "this can help",
  "this makes it possible",
  "in simple terms",
  "simply put",
  "put simply",
  "in other words",
  "to put it simply",
  "it is worth mentioning that",
  "it is important to understand that",
  "it is important to recognize that",
  "it is essential to understand that",
  "it is crucial to understand that",
  "one of the most important",
  "one of the key factors",
  "one of the key aspects",
  "one of the main reasons",
  "one of the most significant",
  "a key factor",
  "a key aspect",
  "a key component",
  "a key element",
  "an important factor",
  "an important aspect",
  "an important component",
  "a significant factor",
  "a significant aspect",
  "a significant component",
  "a fundamental aspect",
  "a fundamental component",
  "a critical factor",
  "a critical aspect",
  "a critical component",
  "it can be seen that",
  "it can be observed that",
  "it can be understood that",
  "it is evident that",
  "it is apparent that",
  "it is clear from",
  "evidence suggests that",
  "research suggests that",
  "studies have shown that",
  "research has shown that",
  "this suggests that",
  "this indicates that",
  "this demonstrates",
  "this illustrates",
  "this highlights",
  "this emphasizes",
  "this emphasises",
  "this reinforces",
  "this reflects",
  "this contributes to",
  "this is particularly relevant",
  "this is particularly important",
  "clear and concise",
  "clear, concise, and",
  "simple and effective",
  "effective and efficient",
  "safe and secure",
  "flexible and scalable",
  "powerful and versatile",
  "efficient and effective",
  "seamless and efficient",
  "reliable and efficient",
  "meaningful and impactful",
  "practical and effective",
  "accessible and user-friendly",
  "user-friendly and accessible",
  "easy to understand",
  "easy to use",
  "straightforward and effective"
];

export const HUMAN_SIGNALS = [
  "i think",
  "i feel",
  "i believe",
  "in my opinion",
  "personally",
  "honestly",
  "to be honest",
  "if you ask me",
  "from my experience",
  "in my experience",
  "i reckon",
  "i guess",
  "i suppose",
  "as far as i can tell",
  "from what i can tell",
  "i would say",
  "kinda",
  "sort of",
  "kind of",
  "you know",
  "i mean",
  "actually",
  "basically",
  "literally",
  "seriously",
  "anyway",
  "anyways",
  "btw",
  "lol",
  "haha",
  "hahaha",
  "imho",
  "tbh",
  "imo",
  "well,",
  "so,",
  "yeah",
  "yep",
  "nope",
  "nah",
  "ok so",
  "right?",
  "you see",
  "look,",
  "listen,",
  "trust me",
  "not gonna lie",
  "gonna",
  "wanna",
  "gotta",
  "dunno",
  "meh",
  "idk",
  "ain't",
  "i'm not sure",
  "i don't know",
  "i can't remember",
  "don't quote me",
  "maybe",
  "perhaps",
  "probably"
];

function escapeRegExp(str) {
  return str.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function buildPhraseRegex(phrases) {
  const sorted = [...phrases].sort((a, b) => b.length - a.length);
  const pattern = sorted.map(escapeRegExp).join("|");
  return new RegExp("(" + pattern + ")", "gi");
}

/**
 * Returns an array of segments: { text, type: "ai" | "human" | "plain" }
 */
export function highlightText(text) {
  if (!text || !text.trim()) return [{ text: "", type: "plain" }];

  const aiRegex = buildPhraseRegex(AI_PHRASES);
  const humanRegex = buildPhraseRegex(HUMAN_SIGNALS);

  const matches = [];
  let m;
  while ((m = aiRegex.exec(text)) !== null) {
    matches.push({ start: m.index, end: m.index + m[0].length, type: "ai", text: m[0] });
  }
  while ((m = humanRegex.exec(text)) !== null) {
    matches.push({ start: m.index, end: m.index + m[0].length, type: "human", text: m[0] });
  }

  matches.sort((a, b) => a.start - b.start || b.end - a.end);

  const filtered = [];
  let lastEnd = 0;
  for (const match of matches) {
    if (match.start >= lastEnd) {
      filtered.push(match);
      lastEnd = match.end;
    }
  }

  const segments = [];
  let cursor = 0;
  for (const match of filtered) {
    if (match.start > cursor) {
      segments.push({ text: text.slice(cursor, match.start), type: "plain" });
    }
    segments.push({ text: match.text, type: match.type });
    cursor = match.end;
  }
  if (cursor < text.length) {
    segments.push({ text: text.slice(cursor), type: "plain" });
  }

  return segments.length ? segments : [{ text, type: "plain" }];
}